'use strict';

// Reads test-results/results.json produced by Playwright's JSON reporter
// and rewrites SKILL.md, preserving any manually-authored sections
// (Acceptance Criteria, Feature Notes) while refreshing the test-results block.
// Run automatically via: npm test
// Run manually via:      npm run update-skill

const fs   = require('fs');
const path = require('path');

const RESULTS_FILE = path.join(__dirname, 'test-results', 'results.json');
const SKILL_FILE   = path.join(__dirname, 'claude', 'test-log.md');

// ── Helpers ──────────────────────────────────────────────────────────────────

function icon(status) {
  return status === 'pass'  ? '✅'
       : status === 'fail'  ? '❌'
       : status === 'skip'  ? '⏭'
       : status === 'flaky' ? '⚠️'
       : '❓';
}

function collectTests(suite, results = []) {
  for (const spec of (suite.specs || [])) {
    for (const test of (spec.tests || [])) {
      const status = test.status === 'expected'   ? 'pass'
                   : test.status === 'unexpected' ? 'fail'
                   : test.status === 'skipped'    ? 'skip'
                   : test.status === 'flaky'      ? 'flaky'
                   : test.status;
      results.push({ file: suite.file || suite.title || '', suite: spec.title || '', status });
    }
  }
  for (const child of (suite.suites || [])) collectTests(child, results);
  return results;
}

// ── Preserve manually-authored sections from existing SKILL.md ───────────────

const PRESERVED_MARKER_START = '<!-- ACCEPTANCE CRITERIA START -->';
const PRESERVED_MARKER_END   = '<!-- ACCEPTANCE CRITERIA END -->';

function extractPreservedSection(existingContent) {
  const start = existingContent.indexOf(PRESERVED_MARKER_START);
  const end   = existingContent.indexOf(PRESERVED_MARKER_END);
  if (start === -1 || end === -1) return null;
  return existingContent.slice(start, end + PRESERVED_MARKER_END.length);
}

const existingSkill  = fs.existsSync(SKILL_FILE) ? fs.readFileSync(SKILL_FILE, 'utf8') : '';
const preservedBlock = extractPreservedSection(existingSkill);

// ── Load results ─────────────────────────────────────────────────────────────

if (!fs.existsSync(RESULTS_FILE)) {
  console.log('update-skill: no results.json found — skipping test-results section update');
  process.exit(0);
}

let data;
try {
  data = JSON.parse(fs.readFileSync(RESULTS_FILE, 'utf8'));
} catch (e) {
  console.error('update-skill: failed to parse results.json —', e.message);
  process.exit(1);
}

const stats      = data.stats || {};
const passed     = stats.expected   ?? 0;
const failed     = stats.unexpected ?? 0;
const skipped    = stats.skipped    ?? 0;
const flaky      = stats.flaky      ?? 0;
const durationMs = stats.duration   ?? 0;
const startTime  = stats.startTime
  ? new Date(stats.startTime).toISOString().replace('T', ' ').slice(0, 19) + ' UTC'
  : 'unknown';

const allTests = (data.suites || []).flatMap(s => collectTests(s));

const byFile = {};
for (const t of allTests) {
  const key = t.file || 'unknown';
  if (!byFile[key]) byFile[key] = [];
  byFile[key].push(t);
}

// ── Build markdown ────────────────────────────────────────────────────────────

const lines = [];

lines.push('# SKILL.md — WTE Playwright Automation');
lines.push('');
lines.push('This file has two sections:');
lines.push('1. **Acceptance Criteria** — updated manually when new feature ZIPs / criteria are provided.');
lines.push('2. **Latest Test Run** — auto-regenerated by `update-skill.js` on every `npm test`.');
lines.push('');

// ── Acceptance Criteria (preserved or default placeholder) ───────────────────
if (preservedBlock) {
  lines.push(preservedBlock);
} else {
  lines.push(PRESERVED_MARKER_START);
  lines.push('## Acceptance Criteria');
  lines.push('');
  lines.push('> Populated by Claude when new plugin ZIPs or feature requirements are provided.');
  lines.push('> Each entry lists the feature, its criteria, and which test file covers it.');
  lines.push('');
  lines.push('_No criteria recorded yet. Share a plugin update or acceptance criteria to get started._');
  lines.push('');
  lines.push(PRESERVED_MARKER_END);
}

lines.push('');
lines.push('---');
lines.push('');

// ── Latest Test Run ───────────────────────────────────────────────────────────
lines.push('## Latest Test Run');
lines.push('');
lines.push('| Stat | Value |');
lines.push('|------|-------|');
lines.push(`| Date | ${startTime} |`);
lines.push(`| Passed | ${passed} |`);
lines.push(`| Failed | ${failed} |`);
lines.push(`| Skipped | ${skipped} |`);
lines.push(`| Flaky | ${flaky} |`);
lines.push(`| Duration | ${(durationMs / 1000).toFixed(1)}s |`);
lines.push('');

if (failed > 0) {
  lines.push('### ❌ Failed Tests');
  lines.push('');
  for (const t of allTests.filter(t => t.status === 'fail')) {
    lines.push(`- ❌ \`${t.file}\` › ${t.suite}`);
  }
  lines.push('');
}

lines.push('### Results by File');
lines.push('');

for (const [file, tests] of Object.entries(byFile)) {
  const fp    = tests.filter(t => t.status === 'fail').length;
  const sp    = tests.filter(t => t.status === 'skip').length;
  const pp    = tests.filter(t => t.status === 'pass').length;
  const label = fp > 0 ? `❌ ${fp} failed`
              : sp === tests.length ? `⏭ all skipped`
              : `✅ ${pp}/${tests.length} passed`;
  lines.push(`#### \`${file}\` — ${label}`);
  lines.push('');
  lines.push('| Status | Test |');
  lines.push('|--------|------|');
  for (const t of tests) {
    lines.push(`| ${icon(t.status)} | ${t.suite} |`);
  }
  lines.push('');
}

lines.push('---');
lines.push('');
lines.push('*Test results auto-generated by [update-skill.js](update-skill.js)*');

// ── Write ─────────────────────────────────────────────────────────────────────

fs.writeFileSync(SKILL_FILE, lines.join('\n'), 'utf8');
console.log(`update-skill: SKILL.md updated (${passed} passed, ${failed} failed, ${skipped} skipped)`);
